apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: mysql
data:
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wordpress

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysql-secret
data:
  MYSQL_ROOT_PASSWORD: NGY4ZWE4ZmRmYTc1NjBkOTdjNTlkMGM4 # 4f8ea8fdfa7560d97c59d0c8
  MYSQL_PASSWORD: cmFoYXNpYQ== # rahasia
  # we need to encode data to base64 