apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:6.2.1-apache
        name: wordpress
        envFrom:
          - configMapRef:
              name: wordpress-config
          - secretRef:
              name: wordpress-secret
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: 1
        livenessProbe:
          failureThreshold: 30
          periodSeconds: 5
          timeoutSeconds: 10
          httpGet:
            path: /
            port: 80
            # httpHeaders:
            # - name: X-Forwarded-Proto
            #   value: https
            # - name: X-Forwarded-Host
            #   value: {{ .host }}
            # - name: Host
            #   value: {{ .host }}
        readinessProbe:
          failureThreshold: 30
          periodSeconds: 5
          timeoutSeconds: 10
          httpGet:
            path: /
            port: 80
            # httpHeaders:
            # - name: X-Forwarded-Proto
            #   value: https
            # - name: X-Forwarded-Host
            #   value: {{ .host }}
            # - name: Host
            #   value: {{ .host }}

      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim